"""Resolver tables after the root-cause round (C4, C6, C11, C14, C16): place aliases never come from a common or
feature word, water bodies and ski areas are named, buoys keep NDBC's case and say what they measure, tickers
never take a market word, college teams carry TheSportsDB ids, and the official-site and geyser tables exist.

The table tests read the committed resolvers/*.jsonl (regenerated by `sourcetool resolvers`); the helper tests
are pure."""
from __future__ import annotations

import json

import pytest

from sourcetool import resolve
from sourcetool.common import read_jsonl
from sourcetool.resolvers import RES, TEAM_ABBREV_STOP, TICKER_STOP, buoy_measures, norm, place_short_forms


def _rows(name: str) -> list[dict]:
    return read_jsonl(RES / f"{name}.jsonl")


def _one(table: str, **match) -> dict:
    return next(r for r in _rows(table) if all(r.get(k) == v for k, v in match.items()))


# --- places: short forms -------------------------------------------------------------------------------

@pytest.mark.parametrize("name,kept", [
    ("Boise City", {"Boise"}), ("Carson City", {"Carson"}), ("Salt Lake City", {"Salt Lake"}),
    ("Winston-Salem", {"Winston"}), ("Butte-Silver Bow", {"Butte"}), ("Anaconda-Deer Lodge County", {"Anaconda"}),
])
def test_place_short_forms_keep_the_names_people_say(name, kept):
    assert place_short_forms(name) == kept


@pytest.mark.parametrize("name", ["Lake City", "Mountain City", "Bay City", "Rapid City", "Panama City",
                                  "Atlantic City", "Junction City", "Dodge City", "Oklahoma City", "Hi-Nella"])
def test_place_short_forms_never_a_common_or_feature_word(name):
    assert place_short_forms(name) == set()


def test_lake_city_michigan_is_not_lake_michigan():
    lc = _one("place", name="Lake City", state="MI")
    assert not {"lake", "lake mi", "lake michigan"} & set(lc["aliases"])
    assert {"lake city", "lake city mi", "lake city michigan"} <= set(lc["aliases"])


def test_no_place_is_called_mountain_or_lake_unless_that_is_its_name():
    for word in ("mountain", "lake", "bay", "beach", "atlantic"):
        assert not [p["id"] for p in _rows("place") if word in p["aliases"] and norm(p["name"]) != word], word


def test_boise_keeps_its_short_name_with_the_state():
    boise = _one("place", name="Boise City", state="ID")
    assert {"boise", "boise id", "boise idaho"} <= set(boise["aliases"])


# --- water bodies and ski areas ------------------------------------------------------------------------

def test_water_bodies_are_their_own_table():
    names = {e["name"] for e in _rows("water_body")}
    assert {"Lake Superior", "Lake Michigan", "Lake Huron", "Lake Erie", "Lake Ontario", "Chesapeake Bay",
            "Puget Sound", "Great Salt Lake"} <= names
    for e in _rows("water_body"):
        assert e["lat"] is not None and e["lon"] is not None and e["attrs"]["type"], e["id"]


def test_a_water_body_never_shares_an_alias_with_a_place():
    places = {a for p in _rows("place") for a in p["aliases"]}
    assert not [(e["name"], a) for e in _rows("water_body") for a in e["aliases"] if a in places]


def test_lake_michigan_is_water_and_milwaukee_is_the_place():
    ask = "Lake Michigan water temp Milwaukee"
    w = resolve.by_name("water_body", ask)
    assert w["status"] == "resolved" and w["best"]["name"] == "Lake Michigan"
    p = resolve.by_name("place", ask)
    assert p["best"] and p["best"]["name"] == "Milwaukee" and p["best"]["state"] == "WI"


def test_mammoth_mountain_is_mammoth_lakes():
    r = resolve.by_name("place", "snow forecast Mammoth Mountain")
    assert r["status"] == "resolved" and (r["best"]["name"], r["best"]["state"]) == ("Mammoth Lakes", "CA")
    assert "mammoth mountain" in r["best"]["attrs"]["nicknames"]  # a place on its own, without "in"


# --- buoys ---------------------------------------------------------------------------------------------

LATEST_HEAD = "#STN LAT LON YYYY MM DD hh mm WDIR WSPD GST WVHT DPD APD MWD PRES PTDY ATMP WTMP DEWP VIS TIDE".split()


def test_buoy_measures_are_the_columns_with_a_reading():
    row = "45013 43.098 -87.850 2026 09 29 15 00 170 2.0 2.0 0.1 MM MM 128 1018.3 +0.0 16.7 17.0 15.7 MM MM".split()
    assert buoy_measures(LATEST_HEAD, row) == ["WDIR", "WSPD", "GST", "WVHT", "MWD", "PRES", "PTDY", "ATMP",
                                               "WTMP", "DEWP"]
    assert buoy_measures(LATEST_HEAD, row[:8] + ["MM"] * 14) == []


def test_buoys_keep_ndbc_case_and_say_what_they_measure():
    b = {e["key"]: e for e in _rows("buoy")}
    assert {"WVHT", "WTMP"} <= set(b["45013"]["attrs"]["measures"])  # Milwaukee Atwater, 8 km off the city
    assert "WVHT" in b["44099"]["attrs"]["measures"]  # Cape Henry, for Virginia Beach surf
    assert all(k == k.upper() and e["id"] == f"buoy:{k}" for k, e in b.items())
    assert all(e["attrs"].get("measures") for e in b.values())  # a station that reports nothing is dropped


# --- tickers -------------------------------------------------------------------------------------------

def test_ticker_aliases_never_take_a_market_word():
    t = {e["key"]: e for e in _rows("ticker")}
    assert "nasdaq" not in t["NDAQ"]["aliases"] and {"ndaq", "nasdaq inc"} <= set(t["NDAQ"]["aliases"])
    assert "dow" in t["DOW"]["aliases"]  # its own symbol stays (the matcher wants it typed like a code)
    bad = [(k, sorted(set(e["aliases"]) & TICKER_STOP)) for k, e in t.items()
           if set(e["aliases"]) & TICKER_STOP - {norm(k)}]
    assert not bad, bad[:10]


# --- teams ---------------------------------------------------------------------------------------------

def test_college_teams_carry_thesportsdb_ids():
    bama = _one("team_espn", id="team_espn:football/college-football/333")
    assert bama["attrs"]["tsdb_id"] == "136168"
    college = [e for e in _rows("team_espn") if e["attrs"].get("league", "").startswith(("college", "mens-college"))]
    assert sum(1 for e in college if e["attrs"].get("tsdb_id")) >= 100


def test_a_thesportsdb_team_is_one_team_of_its_league():
    """Two schools of a name ("Charlotte 49ers", "Charlotte Saints") never share the team TheSportsDB found."""
    names: dict[tuple, set] = {}
    for e in _rows("team_espn"):
        if e["attrs"].get("tsdb_id"):
            names.setdefault((e["attrs"]["league"], e["attrs"]["tsdb_id"]), set()).add(e["name"])
    assert not {k: v for k, v in names.items() if len(v) > 1}
    football = [e for e in _rows("team_espn") if e["attrs"]["league"] == "college-football"]
    assert {e["name"]: e["attrs"].get("tsdb_id") for e in football if e["name"].startswith("Charlotte ")} == {
        "Charlotte 49ers": "136876", "Charlotte Saints": None}


# --- official sites and geysers ------------------------------------------------------------------------

def test_official_sites_name_first_party_domains():
    by = {norm(e["name"]): e for e in _rows("official_site")}
    assert {"slack.com", "slack-status.com"} <= set(by["slack"]["attrs"]["domains"])
    assert "powerball.com" in by["powerball"]["attrs"]["domains"]
    assert "githubstatus.com" in by["github"]["attrs"]["domains"]  # from the Statuspage hosts
    assert all(e["kind"] == "domain" and e["attrs"]["domains"] for e in by.values())
    r = resolve.by_name("official_site", "is Slack down")
    assert r["best"] and r["best"]["name"] == "Slack"


GEYSERS = {"2": "ee5bf30e-4594-4bc0-91ce-452b603743ea", "5": "56165001-1957-4b70-8e02-9d09ad268fb0",
           "13": "9e28b793-f2c1-440f-a39f-3e62b74e2c9a", "4": "590211c7-8dd7-44be-83c3-88aa867a75c0",
           "7": "bf68ab69-5568-48c2-97d0-7debe3f30627", "16": "bdcc6284-9e03-4ee4-a98b-80413474ff96",
           "1": "", "3": "", "10": "", "14": "", "15": "", "163": "", "8": ""}


def test_geysers_carry_geysertimes_and_nps_ids():
    g = {e["attrs"]["gt_id"]: e for e in _rows("geyser")}
    assert set(g) == set(GEYSERS)
    for gt, nps in GEYSERS.items():
        e = g[gt]
        assert e["kind"] == "station" and e["lat"] and e["lon"]
        assert e["attrs"].get("nps_id", "") == nps, gt
        assert norm(e["name"]).endswith(" geyser") and norm(e["name"]) in e["aliases"]
    assert "old faithful" in g["2"]["aliases"]
    assert "grand" not in g["13"]["aliases"]  # "grand" alone is a word, not a geyser
    assert resolve.by_name("geyser", "when does Old Faithful erupt")["best"]["attrs"]["gt_id"] == "2"
    assert resolve.by_name("geyser", "Grand Geyser prediction")["best"]["attrs"]["gt_id"] == "13"


# --- regressions from the live round (2026-10-03): full place names and team nicknames stay -----------

@pytest.mark.parametrize("ask,name,state", [
    ("wave heights Cape Canaveral", "Cape Canaveral", "FL"),
    ("surf height Wrightsville Beach", "Wrightsville Beach", "NC"),
    ("surface water temp Daytona Beach", "Daytona Beach", "FL"),
    ("Blizzard watch for Bismarck", "Bismarck", "ND"),
    ("blizzard alert North Platte", "North Platte", "NE"),
])
def test_a_place_said_by_its_full_name_is_that_place(ask, name, state):
    r = resolve.by_name("place", ask)
    assert r["best"] and (r["best"]["name"], r["best"]["state"]) == (name, state), r["reason"]


def test_rockaway_beach_is_a_place_and_monterey_bay_is_water():
    r = resolve.by_name("place", "Rockaway Beach waves today")
    assert {c["name"] for c in r["candidates"]} == {"Rockaway Beach"}  # OR and MO: a question, never dropped
    w = resolve.by_name("water_body", "Monterey Bay water temp")
    assert w["best"] and w["best"]["name"] == "Monterey Bay"


@pytest.mark.parametrize("table", ["team_espn", "team_mlb", "team_nhl"])
def test_a_team_abbreviation_is_never_an_everyday_word(table):
    bad = [(e["name"], a) for e in _rows(table) for a in e["aliases"]
           if a in TEAM_ABBREV_STOP and a not in norm(e["name"]).split()]
    assert not bad, bad[:10]
    if table == "team_espn":
        assert "win" not in _one(table, name="Winthrop Eagles")["aliases"]
        assert resolve.by_name(table, "did we win last night")["status"] == "none"


@pytest.mark.parametrize("table", ["team_espn", "team_mlb"])
@pytest.mark.parametrize("ask,name", [("did the dbacks win yesterday", "Arizona Diamondbacks"),
                                      ("did the d-backs win", "Arizona Diamondbacks"),
                                      ("Did the A's win?", "Athletics"),
                                      ("how did the Phils do", "Philadelphia Phillies"),
                                      ("did the Nats win", "Washington Nationals")])
def test_mlb_nicknames_name_their_team(table, ask, name):
    r = resolve.by_name(table, ask)
    assert r["best"] and r["best"]["name"] == name and r["best"]["attrs"]["league"] == "mlb", r["reason"]


@pytest.mark.parametrize("ask,name", [
    ("niners score", "San Francisco 49ers"), ("did the Pats win", "New England Patriots"),
    ("sixers game tonight", "Philadelphia 76ers"), ("cavs score", "Cleveland Cavaliers"),
    ("Habs game tonight", "Montreal Canadiens"), ("did the Leafs win", "Toronto Maple Leafs"),
])
def test_pro_nicknames_name_their_team(ask, name):
    r = resolve.by_name("team_espn", ask)
    assert r["best"] and r["best"]["name"] == name, r["reason"]


def test_reviewed_team_nicknames_are_never_a_bare_common_word():
    reviewed = json.loads((RES / "team_nicknames.json").read_text())["entries"]
    said = [norm(n) for e in reviewed for n in e["nicknames"]]
    assert not [n for n in said if n in TEAM_ABBREV_STOP or n in resolve._ENGLISH]
    # every entry finds its club in ESPN's table, and in the league's own table where there is one
    for table in ("team_espn", "team_mlb", "team_nhl"):
        leagues = {e["attrs"]["league"] for e in _rows(table)}
        for e in reviewed:
            if e["league"] in leagues:
                hit = [t for t in _rows(table)
                       if t["attrs"]["league"] == e["league"] and norm(e["club"]) in t["aliases"]]
                assert len(hit) == 1, (table, e)
                assert {norm(n) for n in e["nicknames"]} <= set(hit[0]["attrs"]["nicknames"]), (table, e)


# --- places: coast marks (resolvers._add_coast) ---------------------------------------------------------

@pytest.mark.parametrize("name,state,coastal,great_lakes", [
    ("Duluth", "GA", False, False),  # Atlanta's suburb: no marine source
    ("Duluth", "MN", False, True),  # Lake Superior, not the ocean
    ("Chicago", "IL", False, True), ("Cleveland", "OH", False, True),
    ("Nags Head", "NC", True, False), ("Cape Canaveral", "FL", True, False), ("Miami", "FL", True, False),
    ("San Francisco", "CA", True, False),  # its Census point lies out on the water
    ("Massena", "NY", False, False),  # the St. Lawrence above tide is not the ocean coast
    ("Atlanta", "GA", False, False), ("Sacramento", "CA", False, False),
])
def test_places_say_whether_they_are_on_the_ocean_coast_or_a_great_lake(name, state, coastal, great_lakes):
    p = _one("place", name=name, state=state)
    assert p["attrs"]["coastal"] is coastal
    assert p["attrs"].get("great_lakes", False) is great_lakes


def test_every_place_has_a_coast_mark_and_none_is_both():
    rows = _rows("place")
    assert all(isinstance(p["attrs"].get("coastal"), bool) for p in rows)
    assert not [p["id"] for p in rows if p["attrs"]["coastal"] and p["attrs"].get("great_lakes")]
    assert all(p["attrs"].get("great_lakes", True) is True for p in rows)  # written only when true


def test_shore_distance_and_land_test_on_a_square():
    from sourcetool.resolvers import _near_shore, _on_land, _shore_grid
    square = [[-80.0, 30.0], [-79.0, 30.0], [-79.0, 31.0], [-80.0, 31.0], [-80.0, 30.0]]
    grid = _shore_grid([square])
    assert _near_shore(grid, 30.5, -80.2, 25.0)  # ~19 km west of the edge
    assert not _near_shore(grid, 30.5, -80.5, 25.0)  # ~48 km
    assert _near_shore(grid, 30.5, -79.5, 50.0) and not _near_shore(grid, 30.5, -79.5, 25.0)  # the middle
    bands = {}
    for e in zip(square, square[1:]):
        for b in range(int(min(e[0][1], e[1][1])), int(max(e[0][1], e[1][1])) + 1):
            bands.setdefault(b, []).append(e)
    assert _on_land(bands, 30.5, -79.5) and not _on_land(bands, 30.5, -80.5)


# --- soccer competitions -------------------------------------------------------------------------------

def test_champions_league_is_a_full_alias_of_cl():
    assert "champions league" in _one("soccer_competition", key="CL")["aliases"]
    r = resolve.by_name("soccer_competition", "champions league table")
    assert r["best"] and r["best"]["key"] == "CL", r


@pytest.mark.parametrize("ask,key", [
    ("premier league table", "PL"), ("epl scores", "PL"), ("la liga standings", "PD"), ("laliga fixtures", "PD"),
    ("primera division table", "PD"), ("euros 2028", "EC"), ("euro championship 2028", "EC"), ("ucl final", "CL"),
])
def test_each_soccer_name_people_say_is_its_own_alias(ask, key):
    r = resolve.by_name("soccer_competition", ask)
    assert r["best"] and r["best"]["key"] == key, r


def test_euro_the_currency_is_never_a_competition():
    assert resolve.by_name("soccer_competition", "euro to dollar")["status"] == "none"
    assert not [e["id"] for e in _rows("soccer_competition") if "euro" in e["aliases"]]
